usage:
	@echo "usage: make [edit|web|kill]"

edit e:
	@echo "make (edit) [1|2|4|5|7]"

e15:
	vi demo15.html

web w:
	open http://localhost:8080

run r:
	simplehttpserver &

kill k:
	pkill simplehttpserver