#
# Makefile for node.js using worker thread
#
usage:
	@echo "usage: make [edit|run|test]"

edit e:
	vi test.js

run r:
	node --experimental-worker test.js

test t:
	node --experimental-worker test2.js

