

usage:
	@echo "usage: make [edit|web|kill]"

edit e:
	@echo "make (edit) [1|2|4|5|7]"

e1:
	vi demo1.html
e2:
	vi demo2.html
e4:
	vi demo4.html
e5:
	vi demo5.html
e7:
	vi demo7.html

web w:
	open http://localhost:8080

run r:
	simplehttpserver &

kill k:
	pkill simplehttpserver


